services:
  email-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: email-backend
    restart: unless-stopped
    networks:
      - email-main_app-network
    volumes:
      - ./backend:/app

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: unless-stopped
    networks:
      - email-main_app-network

  caddy:
    image: caddy:2.7.4
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - email-main_app-network
    volumes:
      - ./caddy-config/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend-app
      - email-backend

networks:
  email-main_app-network:
    external: true

volumes:
  caddy_data:
  caddy_config:
